[package]
name = "huon"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.228", features = ["derive"] }
thiserror = "2.0.17"

[lints.clippy]
"pedantic" = "warn"

[dev-dependencies]
pretty_assertions = "1.4.1"
